name: Build Windows Executable for EazyYT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Empacotar com PyInstaller via Wine
      - name: Package EazyYT with PyInstaller
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          # Diretório contendo seu script ou .spec
          path: .
          # Se você tiver um requirements.txt na raiz, instala as deps
          requirements: requirements.txt

      # 3. Fazer upload do .exe gerado
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: EazyYT-windows
          path: dist/windows
